// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: api/codexpulse/core/v1/core.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_Handshake_FullMethodName                 = "/codexpulse.core.v1.CoreService/Handshake"
	CoreService_Bootstrap_FullMethodName                 = "/codexpulse.core.v1.CoreService/Bootstrap"
	CoreService_Contracts_FullMethodName                 = "/codexpulse.core.v1.CoreService/Contracts"
	CoreService_UsageCost_FullMethodName                 = "/codexpulse.core.v1.CoreService/UsageCost"
	CoreService_ListSessions_FullMethodName              = "/codexpulse.core.v1.CoreService/ListSessions"
	CoreService_SessionDetail_FullMethodName             = "/codexpulse.core.v1.CoreService/SessionDetail"
	CoreService_ListProjects_FullMethodName              = "/codexpulse.core.v1.CoreService/ListProjects"
	CoreService_ProjectDetail_FullMethodName             = "/codexpulse.core.v1.CoreService/ProjectDetail"
	CoreService_QuotaCurrent_FullMethodName              = "/codexpulse.core.v1.CoreService/QuotaCurrent"
	CoreService_RequestQuotaRefresh_FullMethodName       = "/codexpulse.core.v1.CoreService/RequestQuotaRefresh"
	CoreService_ListSources_FullMethodName               = "/codexpulse.core.v1.CoreService/ListSources"
	CoreService_Source_FullMethodName                    = "/codexpulse.core.v1.CoreService/Source"
	CoreService_ListJobs_FullMethodName                  = "/codexpulse.core.v1.CoreService/ListJobs"
	CoreService_Job_FullMethodName                       = "/codexpulse.core.v1.CoreService/Job"
	CoreService_ListHealth_FullMethodName                = "/codexpulse.core.v1.CoreService/ListHealth"
	CoreService_Health_FullMethodName                    = "/codexpulse.core.v1.CoreService/Health"
	CoreService_HealthProjection_FullMethodName          = "/codexpulse.core.v1.CoreService/HealthProjection"
	CoreService_DataHealth_FullMethodName                = "/codexpulse.core.v1.CoreService/DataHealth"
	CoreService_Settings_FullMethodName                  = "/codexpulse.core.v1.CoreService/Settings"
	CoreService_UpdateSettings_FullMethodName            = "/codexpulse.core.v1.CoreService/UpdateSettings"
	CoreService_PlanHomeSwitch_FullMethodName            = "/codexpulse.core.v1.CoreService/PlanHomeSwitch"
	CoreService_ConfirmHomeSwitch_FullMethodName         = "/codexpulse.core.v1.CoreService/ConfirmHomeSwitch"
	CoreService_RecoverHomeSwitch_FullMethodName         = "/codexpulse.core.v1.CoreService/RecoverHomeSwitch"
	CoreService_RunRuntimeAction_FullMethodName          = "/codexpulse.core.v1.CoreService/RunRuntimeAction"
	CoreService_AnalyzeSessionIndexRepair_FullMethodName = "/codexpulse.core.v1.CoreService/AnalyzeSessionIndexRepair"
	CoreService_NotifyLifecycle_FullMethodName           = "/codexpulse.core.v1.CoreService/NotifyLifecycle"
	CoreService_MigrationRecoveryState_FullMethodName    = "/codexpulse.core.v1.CoreService/MigrationRecoveryState"
	CoreService_MigrationRecoveryRetry_FullMethodName    = "/codexpulse.core.v1.CoreService/MigrationRecoveryRetry"
	CoreService_MigrationRecoveryPrepare_FullMethodName  = "/codexpulse.core.v1.CoreService/MigrationRecoveryPrepare"
	CoreService_MigrationRecoveryConfirm_FullMethodName  = "/codexpulse.core.v1.CoreService/MigrationRecoveryConfirm"
	CoreService_MigrationRecoveryCancel_FullMethodName   = "/codexpulse.core.v1.CoreService/MigrationRecoveryCancel"
	CoreService_MigrationRecoveryExit_FullMethodName     = "/codexpulse.core.v1.CoreService/MigrationRecoveryExit"
	CoreService_SubscribeInvalidations_FullMethodName    = "/codexpulse.core.v1.CoreService/SubscribeInvalidations"
	CoreService_Shutdown_FullMethodName                  = "/codexpulse.core.v1.CoreService/Shutdown"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService 是 Swift 原生应用与 Go Helper 之间唯一的跨进程业务边界。
type CoreServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
	Contracts(ctx context.Context, in *ContractsRequest, opts ...grpc.CallOption) (*ContractsResponse, error)
	UsageCost(ctx context.Context, in *UsageCostRequest, opts ...grpc.CallOption) (*UsageCostResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*SessionListResponse, error)
	SessionDetail(ctx context.Context, in *SessionDetailRequest, opts ...grpc.CallOption) (*SessionDetailResponse, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ProjectListResponse, error)
	ProjectDetail(ctx context.Context, in *ProjectDetailRequest, opts ...grpc.CallOption) (*ProjectDetailResponse, error)
	QuotaCurrent(ctx context.Context, in *QuotaCurrentRequest, opts ...grpc.CallOption) (*QuotaCurrentResponse, error)
	RequestQuotaRefresh(ctx context.Context, in *QuotaRefreshRequest, opts ...grpc.CallOption) (*QuotaRefreshReceipt, error)
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*SourceListResponse, error)
	Source(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*SourceDetailResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*JobListResponse, error)
	Job(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobDetailResponse, error)
	ListHealth(ctx context.Context, in *ListHealthRequest, opts ...grpc.CallOption) (*HealthListResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthDetailResponse, error)
	HealthProjection(ctx context.Context, in *HealthProjectionRequest, opts ...grpc.CallOption) (*HealthProjectionResponse, error)
	DataHealth(ctx context.Context, in *DataHealthRequest, opts ...grpc.CallOption) (*DataHealthResponse, error)
	Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*SettingsUpdateReceipt, error)
	PlanHomeSwitch(ctx context.Context, in *PlanHomeSwitchRequest, opts ...grpc.CallOption) (*HomeSwitchPlanReceipt, error)
	ConfirmHomeSwitch(ctx context.Context, in *ConfirmHomeSwitchRequest, opts ...grpc.CallOption) (*HomeSwitchReceipt, error)
	RecoverHomeSwitch(ctx context.Context, in *RecoverHomeSwitchRequest, opts ...grpc.CallOption) (*HomeSwitchReceipt, error)
	RunRuntimeAction(ctx context.Context, in *RuntimeActionRequest, opts ...grpc.CallOption) (*RuntimeActionReceipt, error)
	AnalyzeSessionIndexRepair(ctx context.Context, in *AnalyzeSessionIndexRepairRequest, opts ...grpc.CallOption) (*RepairDryRunReceipt, error)
	NotifyLifecycle(ctx context.Context, in *LifecycleNotificationRequest, opts ...grpc.CallOption) (*LifecycleNotificationReceipt, error)
	MigrationRecoveryState(ctx context.Context, in *MigrationRecoveryStateRequest, opts ...grpc.CallOption) (*MigrationRecoverySnapshot, error)
	MigrationRecoveryRetry(ctx context.Context, in *MigrationRecoveryRetryRequest, opts ...grpc.CallOption) (*MigrationRecoveryReceipt, error)
	MigrationRecoveryPrepare(ctx context.Context, in *MigrationRecoveryPrepareRequest, opts ...grpc.CallOption) (*MigrationRestoreConfirmation, error)
	MigrationRecoveryConfirm(ctx context.Context, in *MigrationRecoveryConfirmRequest, opts ...grpc.CallOption) (*MigrationRecoveryReceipt, error)
	MigrationRecoveryCancel(ctx context.Context, in *MigrationRecoveryCancelRequest, opts ...grpc.CallOption) (*Empty, error)
	MigrationRecoveryExit(ctx context.Context, in *MigrationRecoveryExitRequest, opts ...grpc.CallOption) (*Empty, error)
	SubscribeInvalidations(ctx context.Context, in *SubscribeInvalidationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryInvalidationEvent], error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, CoreService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, CoreService_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Contracts(ctx context.Context, in *ContractsRequest, opts ...grpc.CallOption) (*ContractsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractsResponse)
	err := c.cc.Invoke(ctx, CoreService_Contracts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UsageCost(ctx context.Context, in *UsageCostRequest, opts ...grpc.CallOption) (*UsageCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageCostResponse)
	err := c.cc.Invoke(ctx, CoreService_UsageCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*SessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionListResponse)
	err := c.cc.Invoke(ctx, CoreService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SessionDetail(ctx context.Context, in *SessionDetailRequest, opts ...grpc.CallOption) (*SessionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionDetailResponse)
	err := c.cc.Invoke(ctx, CoreService_SessionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ProjectListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectListResponse)
	err := c.cc.Invoke(ctx, CoreService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ProjectDetail(ctx context.Context, in *ProjectDetailRequest, opts ...grpc.CallOption) (*ProjectDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectDetailResponse)
	err := c.cc.Invoke(ctx, CoreService_ProjectDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) QuotaCurrent(ctx context.Context, in *QuotaCurrentRequest, opts ...grpc.CallOption) (*QuotaCurrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaCurrentResponse)
	err := c.cc.Invoke(ctx, CoreService_QuotaCurrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) RequestQuotaRefresh(ctx context.Context, in *QuotaRefreshRequest, opts ...grpc.CallOption) (*QuotaRefreshReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaRefreshReceipt)
	err := c.cc.Invoke(ctx, CoreService_RequestQuotaRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*SourceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceListResponse)
	err := c.cc.Invoke(ctx, CoreService_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Source(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*SourceDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceDetailResponse)
	err := c.cc.Invoke(ctx, CoreService_Source_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*JobListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, CoreService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Job(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobDetailResponse)
	err := c.cc.Invoke(ctx, CoreService_Job_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ListHealth(ctx context.Context, in *ListHealthRequest, opts ...grpc.CallOption) (*HealthListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthListResponse)
	err := c.cc.Invoke(ctx, CoreService_ListHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthDetailResponse)
	err := c.cc.Invoke(ctx, CoreService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) HealthProjection(ctx context.Context, in *HealthProjectionRequest, opts ...grpc.CallOption) (*HealthProjectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthProjectionResponse)
	err := c.cc.Invoke(ctx, CoreService_HealthProjection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DataHealth(ctx context.Context, in *DataHealthRequest, opts ...grpc.CallOption) (*DataHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataHealthResponse)
	err := c.cc.Invoke(ctx, CoreService_DataHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, CoreService_Settings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*SettingsUpdateReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsUpdateReceipt)
	err := c.cc.Invoke(ctx, CoreService_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) PlanHomeSwitch(ctx context.Context, in *PlanHomeSwitchRequest, opts ...grpc.CallOption) (*HomeSwitchPlanReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeSwitchPlanReceipt)
	err := c.cc.Invoke(ctx, CoreService_PlanHomeSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ConfirmHomeSwitch(ctx context.Context, in *ConfirmHomeSwitchRequest, opts ...grpc.CallOption) (*HomeSwitchReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeSwitchReceipt)
	err := c.cc.Invoke(ctx, CoreService_ConfirmHomeSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) RecoverHomeSwitch(ctx context.Context, in *RecoverHomeSwitchRequest, opts ...grpc.CallOption) (*HomeSwitchReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeSwitchReceipt)
	err := c.cc.Invoke(ctx, CoreService_RecoverHomeSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) RunRuntimeAction(ctx context.Context, in *RuntimeActionRequest, opts ...grpc.CallOption) (*RuntimeActionReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeActionReceipt)
	err := c.cc.Invoke(ctx, CoreService_RunRuntimeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) AnalyzeSessionIndexRepair(ctx context.Context, in *AnalyzeSessionIndexRepairRequest, opts ...grpc.CallOption) (*RepairDryRunReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepairDryRunReceipt)
	err := c.cc.Invoke(ctx, CoreService_AnalyzeSessionIndexRepair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) NotifyLifecycle(ctx context.Context, in *LifecycleNotificationRequest, opts ...grpc.CallOption) (*LifecycleNotificationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifecycleNotificationReceipt)
	err := c.cc.Invoke(ctx, CoreService_NotifyLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) MigrationRecoveryState(ctx context.Context, in *MigrationRecoveryStateRequest, opts ...grpc.CallOption) (*MigrationRecoverySnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationRecoverySnapshot)
	err := c.cc.Invoke(ctx, CoreService_MigrationRecoveryState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) MigrationRecoveryRetry(ctx context.Context, in *MigrationRecoveryRetryRequest, opts ...grpc.CallOption) (*MigrationRecoveryReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationRecoveryReceipt)
	err := c.cc.Invoke(ctx, CoreService_MigrationRecoveryRetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) MigrationRecoveryPrepare(ctx context.Context, in *MigrationRecoveryPrepareRequest, opts ...grpc.CallOption) (*MigrationRestoreConfirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationRestoreConfirmation)
	err := c.cc.Invoke(ctx, CoreService_MigrationRecoveryPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) MigrationRecoveryConfirm(ctx context.Context, in *MigrationRecoveryConfirmRequest, opts ...grpc.CallOption) (*MigrationRecoveryReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationRecoveryReceipt)
	err := c.cc.Invoke(ctx, CoreService_MigrationRecoveryConfirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) MigrationRecoveryCancel(ctx context.Context, in *MigrationRecoveryCancelRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_MigrationRecoveryCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) MigrationRecoveryExit(ctx context.Context, in *MigrationRecoveryExitRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoreService_MigrationRecoveryExit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SubscribeInvalidations(ctx context.Context, in *SubscribeInvalidationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryInvalidationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreService_ServiceDesc.Streams[0], CoreService_SubscribeInvalidations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeInvalidationsRequest, QueryInvalidationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_SubscribeInvalidationsClient = grpc.ServerStreamingClient[QueryInvalidationEvent]

func (c *coreServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, CoreService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService 是 Swift 原生应用与 Go Helper 之间唯一的跨进程业务边界。
type CoreServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error)
	Contracts(context.Context, *ContractsRequest) (*ContractsResponse, error)
	UsageCost(context.Context, *UsageCostRequest) (*UsageCostResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*SessionListResponse, error)
	SessionDetail(context.Context, *SessionDetailRequest) (*SessionDetailResponse, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ProjectListResponse, error)
	ProjectDetail(context.Context, *ProjectDetailRequest) (*ProjectDetailResponse, error)
	QuotaCurrent(context.Context, *QuotaCurrentRequest) (*QuotaCurrentResponse, error)
	RequestQuotaRefresh(context.Context, *QuotaRefreshRequest) (*QuotaRefreshReceipt, error)
	ListSources(context.Context, *ListSourcesRequest) (*SourceListResponse, error)
	Source(context.Context, *SourceRequest) (*SourceDetailResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*JobListResponse, error)
	Job(context.Context, *JobRequest) (*JobDetailResponse, error)
	ListHealth(context.Context, *ListHealthRequest) (*HealthListResponse, error)
	Health(context.Context, *HealthRequest) (*HealthDetailResponse, error)
	HealthProjection(context.Context, *HealthProjectionRequest) (*HealthProjectionResponse, error)
	DataHealth(context.Context, *DataHealthRequest) (*DataHealthResponse, error)
	Settings(context.Context, *SettingsRequest) (*SettingsResponse, error)
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*SettingsUpdateReceipt, error)
	PlanHomeSwitch(context.Context, *PlanHomeSwitchRequest) (*HomeSwitchPlanReceipt, error)
	ConfirmHomeSwitch(context.Context, *ConfirmHomeSwitchRequest) (*HomeSwitchReceipt, error)
	RecoverHomeSwitch(context.Context, *RecoverHomeSwitchRequest) (*HomeSwitchReceipt, error)
	RunRuntimeAction(context.Context, *RuntimeActionRequest) (*RuntimeActionReceipt, error)
	AnalyzeSessionIndexRepair(context.Context, *AnalyzeSessionIndexRepairRequest) (*RepairDryRunReceipt, error)
	NotifyLifecycle(context.Context, *LifecycleNotificationRequest) (*LifecycleNotificationReceipt, error)
	MigrationRecoveryState(context.Context, *MigrationRecoveryStateRequest) (*MigrationRecoverySnapshot, error)
	MigrationRecoveryRetry(context.Context, *MigrationRecoveryRetryRequest) (*MigrationRecoveryReceipt, error)
	MigrationRecoveryPrepare(context.Context, *MigrationRecoveryPrepareRequest) (*MigrationRestoreConfirmation, error)
	MigrationRecoveryConfirm(context.Context, *MigrationRecoveryConfirmRequest) (*MigrationRecoveryReceipt, error)
	MigrationRecoveryCancel(context.Context, *MigrationRecoveryCancelRequest) (*Empty, error)
	MigrationRecoveryExit(context.Context, *MigrationRecoveryExitRequest) (*Empty, error)
	SubscribeInvalidations(*SubscribeInvalidationsRequest, grpc.ServerStreamingServer[QueryInvalidationEvent]) error
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedCoreServiceServer) Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedCoreServiceServer) Contracts(context.Context, *ContractsRequest) (*ContractsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Contracts not implemented")
}
func (UnimplementedCoreServiceServer) UsageCost(context.Context, *UsageCostRequest) (*UsageCostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UsageCost not implemented")
}
func (UnimplementedCoreServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*SessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedCoreServiceServer) SessionDetail(context.Context, *SessionDetailRequest) (*SessionDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionDetail not implemented")
}
func (UnimplementedCoreServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ProjectListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedCoreServiceServer) ProjectDetail(context.Context, *ProjectDetailRequest) (*ProjectDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectDetail not implemented")
}
func (UnimplementedCoreServiceServer) QuotaCurrent(context.Context, *QuotaCurrentRequest) (*QuotaCurrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuotaCurrent not implemented")
}
func (UnimplementedCoreServiceServer) RequestQuotaRefresh(context.Context, *QuotaRefreshRequest) (*QuotaRefreshReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestQuotaRefresh not implemented")
}
func (UnimplementedCoreServiceServer) ListSources(context.Context, *ListSourcesRequest) (*SourceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedCoreServiceServer) Source(context.Context, *SourceRequest) (*SourceDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Source not implemented")
}
func (UnimplementedCoreServiceServer) ListJobs(context.Context, *ListJobsRequest) (*JobListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedCoreServiceServer) Job(context.Context, *JobRequest) (*JobDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Job not implemented")
}
func (UnimplementedCoreServiceServer) ListHealth(context.Context, *ListHealthRequest) (*HealthListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHealth not implemented")
}
func (UnimplementedCoreServiceServer) Health(context.Context, *HealthRequest) (*HealthDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCoreServiceServer) HealthProjection(context.Context, *HealthProjectionRequest) (*HealthProjectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthProjection not implemented")
}
func (UnimplementedCoreServiceServer) DataHealth(context.Context, *DataHealthRequest) (*DataHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataHealth not implemented")
}
func (UnimplementedCoreServiceServer) Settings(context.Context, *SettingsRequest) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Settings not implemented")
}
func (UnimplementedCoreServiceServer) UpdateSettings(context.Context, *UpdateSettingsRequest) (*SettingsUpdateReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedCoreServiceServer) PlanHomeSwitch(context.Context, *PlanHomeSwitchRequest) (*HomeSwitchPlanReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanHomeSwitch not implemented")
}
func (UnimplementedCoreServiceServer) ConfirmHomeSwitch(context.Context, *ConfirmHomeSwitchRequest) (*HomeSwitchReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmHomeSwitch not implemented")
}
func (UnimplementedCoreServiceServer) RecoverHomeSwitch(context.Context, *RecoverHomeSwitchRequest) (*HomeSwitchReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverHomeSwitch not implemented")
}
func (UnimplementedCoreServiceServer) RunRuntimeAction(context.Context, *RuntimeActionRequest) (*RuntimeActionReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method RunRuntimeAction not implemented")
}
func (UnimplementedCoreServiceServer) AnalyzeSessionIndexRepair(context.Context, *AnalyzeSessionIndexRepairRequest) (*RepairDryRunReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeSessionIndexRepair not implemented")
}
func (UnimplementedCoreServiceServer) NotifyLifecycle(context.Context, *LifecycleNotificationRequest) (*LifecycleNotificationReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyLifecycle not implemented")
}
func (UnimplementedCoreServiceServer) MigrationRecoveryState(context.Context, *MigrationRecoveryStateRequest) (*MigrationRecoverySnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationRecoveryState not implemented")
}
func (UnimplementedCoreServiceServer) MigrationRecoveryRetry(context.Context, *MigrationRecoveryRetryRequest) (*MigrationRecoveryReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationRecoveryRetry not implemented")
}
func (UnimplementedCoreServiceServer) MigrationRecoveryPrepare(context.Context, *MigrationRecoveryPrepareRequest) (*MigrationRestoreConfirmation, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationRecoveryPrepare not implemented")
}
func (UnimplementedCoreServiceServer) MigrationRecoveryConfirm(context.Context, *MigrationRecoveryConfirmRequest) (*MigrationRecoveryReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationRecoveryConfirm not implemented")
}
func (UnimplementedCoreServiceServer) MigrationRecoveryCancel(context.Context, *MigrationRecoveryCancelRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationRecoveryCancel not implemented")
}
func (UnimplementedCoreServiceServer) MigrationRecoveryExit(context.Context, *MigrationRecoveryExitRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationRecoveryExit not implemented")
}
func (UnimplementedCoreServiceServer) SubscribeInvalidations(*SubscribeInvalidationsRequest, grpc.ServerStreamingServer[QueryInvalidationEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeInvalidations not implemented")
}
func (UnimplementedCoreServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Bootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Contracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Contracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Contracts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Contracts(ctx, req.(*ContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UsageCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UsageCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UsageCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UsageCost(ctx, req.(*UsageCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SessionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SessionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SessionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SessionDetail(ctx, req.(*SessionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ProjectDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ProjectDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ProjectDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ProjectDetail(ctx, req.(*ProjectDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_QuotaCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).QuotaCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_QuotaCurrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).QuotaCurrent(ctx, req.(*QuotaCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_RequestQuotaRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).RequestQuotaRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_RequestQuotaRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).RequestQuotaRefresh(ctx, req.(*QuotaRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Source_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Source(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Source_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Source(ctx, req.(*SourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Job_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Job(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Job_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Job(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ListHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ListHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ListHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ListHealth(ctx, req.(*ListHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_HealthProjection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthProjectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).HealthProjection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_HealthProjection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).HealthProjection(ctx, req.(*HealthProjectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DataHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DataHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_DataHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DataHealth(ctx, req.(*DataHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Settings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Settings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Settings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Settings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_PlanHomeSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanHomeSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).PlanHomeSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_PlanHomeSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).PlanHomeSwitch(ctx, req.(*PlanHomeSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ConfirmHomeSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmHomeSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ConfirmHomeSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ConfirmHomeSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ConfirmHomeSwitch(ctx, req.(*ConfirmHomeSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_RecoverHomeSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverHomeSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).RecoverHomeSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_RecoverHomeSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).RecoverHomeSwitch(ctx, req.(*RecoverHomeSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_RunRuntimeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).RunRuntimeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_RunRuntimeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).RunRuntimeAction(ctx, req.(*RuntimeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_AnalyzeSessionIndexRepair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeSessionIndexRepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).AnalyzeSessionIndexRepair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_AnalyzeSessionIndexRepair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).AnalyzeSessionIndexRepair(ctx, req.(*AnalyzeSessionIndexRepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_NotifyLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifecycleNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).NotifyLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_NotifyLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).NotifyLifecycle(ctx, req.(*LifecycleNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_MigrationRecoveryState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRecoveryStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).MigrationRecoveryState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_MigrationRecoveryState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).MigrationRecoveryState(ctx, req.(*MigrationRecoveryStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_MigrationRecoveryRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRecoveryRetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).MigrationRecoveryRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_MigrationRecoveryRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).MigrationRecoveryRetry(ctx, req.(*MigrationRecoveryRetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_MigrationRecoveryPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRecoveryPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).MigrationRecoveryPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_MigrationRecoveryPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).MigrationRecoveryPrepare(ctx, req.(*MigrationRecoveryPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_MigrationRecoveryConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRecoveryConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).MigrationRecoveryConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_MigrationRecoveryConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).MigrationRecoveryConfirm(ctx, req.(*MigrationRecoveryConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_MigrationRecoveryCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRecoveryCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).MigrationRecoveryCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_MigrationRecoveryCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).MigrationRecoveryCancel(ctx, req.(*MigrationRecoveryCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_MigrationRecoveryExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRecoveryExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).MigrationRecoveryExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_MigrationRecoveryExit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).MigrationRecoveryExit(ctx, req.(*MigrationRecoveryExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SubscribeInvalidations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeInvalidationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServiceServer).SubscribeInvalidations(m, &grpc.GenericServerStream[SubscribeInvalidationsRequest, QueryInvalidationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_SubscribeInvalidationsServer = grpc.ServerStreamingServer[QueryInvalidationEvent]

func _CoreService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codexpulse.core.v1.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _CoreService_Handshake_Handler,
		},
		{
			MethodName: "Bootstrap",
			Handler:    _CoreService_Bootstrap_Handler,
		},
		{
			MethodName: "Contracts",
			Handler:    _CoreService_Contracts_Handler,
		},
		{
			MethodName: "UsageCost",
			Handler:    _CoreService_UsageCost_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _CoreService_ListSessions_Handler,
		},
		{
			MethodName: "SessionDetail",
			Handler:    _CoreService_SessionDetail_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _CoreService_ListProjects_Handler,
		},
		{
			MethodName: "ProjectDetail",
			Handler:    _CoreService_ProjectDetail_Handler,
		},
		{
			MethodName: "QuotaCurrent",
			Handler:    _CoreService_QuotaCurrent_Handler,
		},
		{
			MethodName: "RequestQuotaRefresh",
			Handler:    _CoreService_RequestQuotaRefresh_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _CoreService_ListSources_Handler,
		},
		{
			MethodName: "Source",
			Handler:    _CoreService_Source_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _CoreService_ListJobs_Handler,
		},
		{
			MethodName: "Job",
			Handler:    _CoreService_Job_Handler,
		},
		{
			MethodName: "ListHealth",
			Handler:    _CoreService_ListHealth_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CoreService_Health_Handler,
		},
		{
			MethodName: "HealthProjection",
			Handler:    _CoreService_HealthProjection_Handler,
		},
		{
			MethodName: "DataHealth",
			Handler:    _CoreService_DataHealth_Handler,
		},
		{
			MethodName: "Settings",
			Handler:    _CoreService_Settings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _CoreService_UpdateSettings_Handler,
		},
		{
			MethodName: "PlanHomeSwitch",
			Handler:    _CoreService_PlanHomeSwitch_Handler,
		},
		{
			MethodName: "ConfirmHomeSwitch",
			Handler:    _CoreService_ConfirmHomeSwitch_Handler,
		},
		{
			MethodName: "RecoverHomeSwitch",
			Handler:    _CoreService_RecoverHomeSwitch_Handler,
		},
		{
			MethodName: "RunRuntimeAction",
			Handler:    _CoreService_RunRuntimeAction_Handler,
		},
		{
			MethodName: "AnalyzeSessionIndexRepair",
			Handler:    _CoreService_AnalyzeSessionIndexRepair_Handler,
		},
		{
			MethodName: "NotifyLifecycle",
			Handler:    _CoreService_NotifyLifecycle_Handler,
		},
		{
			MethodName: "MigrationRecoveryState",
			Handler:    _CoreService_MigrationRecoveryState_Handler,
		},
		{
			MethodName: "MigrationRecoveryRetry",
			Handler:    _CoreService_MigrationRecoveryRetry_Handler,
		},
		{
			MethodName: "MigrationRecoveryPrepare",
			Handler:    _CoreService_MigrationRecoveryPrepare_Handler,
		},
		{
			MethodName: "MigrationRecoveryConfirm",
			Handler:    _CoreService_MigrationRecoveryConfirm_Handler,
		},
		{
			MethodName: "MigrationRecoveryCancel",
			Handler:    _CoreService_MigrationRecoveryCancel_Handler,
		},
		{
			MethodName: "MigrationRecoveryExit",
			Handler:    _CoreService_MigrationRecoveryExit_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _CoreService_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeInvalidations",
			Handler:       _CoreService_SubscribeInvalidations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/codexpulse/core/v1/core.proto",
}
