// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ErrorCode 是跨端有限错误分类。
 */
export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorValidation = "validation",
    ErrorNotFound = "not_found",
    ErrorPartial = "partial",
    ErrorUnavailable = "unavailable",
    ErrorCancelled = "cancelled",
    ErrorDeadlineExceeded = "deadline_exceeded",
    ErrorInternal = "internal",
};

/**
 * ErrorDetail 只暴露稳定分类、i18n key、allowlisted field 和 retryable。
 */
export interface ErrorDetail {
    "code": ErrorCode;
    "messageKey": string;
    "field": string | null;
    "retryable": boolean;
}

/**
 * ErrorEnvelope 是 fatal query failure 的版本化跨端 envelope。
 */
export interface ErrorEnvelope {
    "version": string;
    "error": ErrorDetail;
}

/**
 * FilterOperator 是业务字段筛选操作，不映射任意 SQL 操作符。
 */
export enum FilterOperator {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FilterEqual = "eq",
    FilterNotEqual = "not_eq",
    FilterIn = "in",
    FilterGreaterThan = "gt",
    FilterAtLeast = "gte",
    FilterLessThan = "lt",
    FilterAtMost = "lte",
    FilterContains = "contains",
    FilterIsNull = "is_null",
    FilterIsNotNull = "is_not_null",
};

/**
 * FilterTerm 只携带稳定业务值；具体类型转换由业务 query service 负责。
 */
export interface FilterTerm {
    "field": string;
    "operator": FilterOperator;
    "values": string[] | null;
}

/**
 * Issue 是非 fatal partial/unavailable 说明，不携带底层 error text。
 */
export interface Issue {
    "code": ErrorCode;
    "messageKey": string;
    "retryable": boolean;
}

/**
 * LocalDateRange 使用本地日和 IANA timezone 表达用户选择范围。
 */
export interface LocalDateRange {
    "startDate": string;
    "endDateExclusive": string;
    "timeZone": string;
}

/**
 * NumericUnit 固定跨端整数的业务单位，不允许无单位 number。
 */
export enum NumericUnit {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NumericTokens = "tokens",
    NumericMicroUSD = "micro_usd",
    NumericCount = "count",
    NumericBytes = "bytes",
    NumericMilliseconds = "milliseconds",
};

/**
 * NumericValue 使用 value/reason xor 区分 unknown 与真实零。
 */
export interface NumericValue {
    "value": number | null;
    "unit": NumericUnit;
    "unknownReason": UnknownReason | null;
}

/**
 * PageInfo 描述当前页和不透明下一页 cursor。
 */
export interface PageInfo {
    "limit": number;
    "hasMore": boolean;
    "nextCursor": string | null;
}

/**
 * PageRequest 使用有界 limit 和不透明 cursor；cursor 的业务 payload 由具体 endpoint 拥有。
 */
export interface PageRequest {
    "cursor": string | null;
    "limit": number;
}

/**
 * Request 是跨页面公共查询输入 envelope。
 */
export interface Request {
    "page": PageRequest;
    "sort": SortTerm[] | null;
    "filters": FilterTerm[] | null;
    "timeRange": LocalDateRange | null;
}

/**
 * ResponseMeta 是业务 response 组合的公共版本、状态和分页元数据。
 */
export interface ResponseMeta {
    "version": string;
    "status": ResponseStatus;
    "page": PageInfo | null;
    "issues": Issue[] | null;
}

/**
 * ResponseStatus 区分完整、部分和当前不可用，不把任一状态折成空集合。
 */
export enum ResponseStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ResponseComplete = "complete",
    ResponsePartial = "partial",
    ResponseUnavailable = "unavailable",
};

/**
 * SortDirection 是有限排序方向。
 */
export enum SortDirection {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SortAscending = "asc",
    SortDescending = "desc",
};

/**
 * SortTerm 指向 endpoint specification 中声明的业务字段。
 */
export interface SortTerm {
    "field": string;
    "direction": SortDirection;
}

/**
 * UTCTimeRange 是 LocalDateRange 归一化后的 UTC 半开区间。
 */
export interface UTCTimeRange {
    "startAtMs": number;
    "endAtMs": number;
    "timeZone": string;
}

/**
 * UnknownReason 区分从未加载、不适用、暂不可用和尚未计算。
 */
export enum UnknownReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UnknownNeverLoaded = "never_loaded",
    UnknownNotApplicable = "not_applicable",
    UnknownUnavailable = "unavailable",
    UnknownNotComputed = "not_computed",
};
