// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pricing$0 from "../../pricing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../models.js";

export interface AttributionValue {
    "id": string | null;
    "displayName": string | null;
    "confidence": string;
    "source": string;
    "reason": string;
}

export enum DegradedReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DegradedRollupMissing = "rollup_missing",

    DegradedRollupAmbiguous = "rollup_ambiguous",
};

export interface ProjectDailyPoint {
    "bucketStartAtMs": query$0.NumericValue;
    "confidence": string;
    "source": string;
    "reason": string;
    "totals": UsageTotals;
}

export interface ProjectDetailRequest {
    "dimensionKey": string;
    "range": query$0.LocalDateRange;
    "sessionPage": query$0.PageRequest;
    "modelPage": query$0.PageRequest;
}

export interface ProjectDetailResponse {
    "meta": query$0.ResponseMeta;
    "range": query$0.UTCTimeRange;
    "reportingTimeZone": string;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "item": ProjectItem;
    "daily": ProjectDailyPoint[] | null;
    "sessionPage": query$0.PageInfo;
    "sessions": ProjectSessionItem[] | null;
    "modelPage": query$0.PageInfo;
    "models": ProjectModelItem[] | null;
    "globalTotals": UsageTotals;
}

export interface ProjectItem {
    "dimensionKey": string;
    "project": AttributionValue;
    "sessionCount": query$0.NumericValue;
    "trend": ProjectDailyPoint[] | null;
    "totals": UsageTotals;
}

export interface ProjectListResponse {
    "meta": query$0.ResponseMeta;
    "range": query$0.UTCTimeRange;
    "reportingTimeZone": string;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "items": ProjectItem[] | null;
    "matchedCount": query$0.NumericValue;
    "globalTotals": UsageTotals;
    "matchedTotals": UsageTotals;
    "pageTotals": UsageTotals;
}

export interface ProjectModelItem {
    "dimensionKey": string;
    "model": AttributionValue;
    "totals": UsageTotals;
}

export interface ProjectSessionItem {
    "sessionId": string;
    "displayTitle": string;
    "titleConfidence": string;
    "titleSource": string;
    "titleReason": string;
    "model": AttributionValue;
    "activity": string;
    "lastActivityAtMs": query$0.NumericValue;
    "totals": UsageTotals;
}

export interface ReasonCount {
    "reason": pricing$0.CostReason;
    "count": query$0.NumericValue;
}

export interface SessionDetailRequest {
    "sessionId": string;
    "reportingTimezone": string | null;
    "turnPage": query$0.PageRequest;
}

export interface SessionDetailResponse {
    "meta": query$0.ResponseMeta;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "unpricedReasons": ReasonCount[] | null;
    "item": SessionItem;
    "turnPage": query$0.PageInfo;
    "turns": SessionTurnItem[] | null;
    "degradedReason": DegradedReason | null;
}

export interface SessionItem {
    "sessionId": string;
    "displayTitle": string;
    "titleConfidence": string;
    "titleSource": string;
    "titleReason": string;
    "project": AttributionValue;
    "model": AttributionValue;
    "activity": string;
    "lastActivityAtMs": query$0.NumericValue;
    "totals": UsageTotals;
}

export interface SessionListResponse {
    "meta": query$0.ResponseMeta;
    "pricingSource": string | null;
    "currency": string | null;
    "items": SessionItem[] | null;
    "matchedCount": query$0.NumericValue;
    "matchedTotals": UsageTotals;
    "pageTotals": UsageTotals;
    "degradedReason": DegradedReason | null;
}

/**
 * SessionTurnItem 是content-free turn usage/cost时间线条目。
 */
export interface SessionTurnItem {
    "timelineKey": string;
    "state": SessionTurnState;
    "model": AttributionValue;
    "startedAtMs": query$0.NumericValue;
    "completedAtMs": query$0.NumericValue;
    "observedAtMs": query$0.NumericValue;
    "totals": UsageTotals;
    "pricingStatus": SessionTurnPricingStatus;
    "pricingVersion": string | null;
    "unpricedReason": pricing$0.CostReason | null;
}

/**
 * SessionTurnPricingStatus 区分尚不可定价、已定价和明确未定价。
 */
export enum SessionTurnPricingStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionTurnPricingUnknown = "unknown",
    SessionTurnPricingPriced = "priced",
    SessionTurnPricingUnpriced = "unpriced",
};

/**
 * SessionTurnState 只表达安全的turn lifecycle，不推导业务状态机。
 */
export enum SessionTurnState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionTurnActive = "active",
    SessionTurnComplete = "complete",
};

export enum TrendGranularity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TrendDay = "day",
    TrendWeek = "week",
    TrendMonth = "month",
};

export interface TrendPoint {
    "key": string;
    "startAtMs": query$0.NumericValue;
    "endAtMs": query$0.NumericValue;
    "totals": UsageTotals;
}

export interface UsageCostRequest {
    "range": query$0.LocalDateRange;
    "granularity": TrendGranularity;
}

export interface UsageCostResponse {
    "meta": query$0.ResponseMeta;
    "range": query$0.UTCTimeRange;
    "reportingTimeZone": string;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "totals": UsageTotals;
    "trend": TrendPoint[] | null;
    "unpricedReasons": ReasonCount[] | null;
    "degradedReason": DegradedReason | null;
}

export interface UsageTotals {
    "turnCount": query$0.NumericValue;
    "inputTokens": query$0.NumericValue;
    "cachedInputTokens": query$0.NumericValue;
    "outputTokens": query$0.NumericValue;
    "reasoningTokens": query$0.NumericValue;
    "totalTokens": query$0.NumericValue;
    "estimatedUsdMicros": query$0.NumericValue;
    "pricedTurnCount": query$0.NumericValue;
    "unpricedTurnCount": query$0.NumericValue;
    "firstActivityAtMs": query$0.NumericValue;
    "lastActivityAtMs": query$0.NumericValue;
}
