// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pricing$0 from "../../pricing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../models.js";

export interface AttributionValue {
    "id": string | null;
    "displayName": string | null;
    "confidence": string;
    "source": string;
    "reason": string;
}

export enum DegradedReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DegradedRollupMissing = "rollup_missing",

    DegradedRollupAmbiguous = "rollup_ambiguous",
};

export interface ProjectDailyPoint {
    "bucketStartAtMs": query$0.NumericValue;
    "confidence": string;
    "source": string;
    "reason": string;
    "totals": UsageTotals;
}

export interface ProjectDetailRequest {
    "dimensionKey": string;
    "range": query$0.LocalDateRange;
}

export interface ProjectDetailResponse {
    "meta": query$0.ResponseMeta;
    "range": query$0.UTCTimeRange;
    "reportingTimeZone": string;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "item": ProjectItem;
    "daily": ProjectDailyPoint[] | null;
    "globalTotals": UsageTotals;
}

export interface ProjectItem {
    "dimensionKey": string;
    "project": AttributionValue;
    "totals": UsageTotals;
}

export interface ProjectListResponse {
    "meta": query$0.ResponseMeta;
    "range": query$0.UTCTimeRange;
    "reportingTimeZone": string;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "items": ProjectItem[] | null;
    "matchedCount": query$0.NumericValue;
    "globalTotals": UsageTotals;
    "matchedTotals": UsageTotals;
    "pageTotals": UsageTotals;
}

export interface ReasonCount {
    "reason": pricing$0.CostReason;
    "count": query$0.NumericValue;
}

export interface SessionDetailRequest {
    "sessionId": string;
    "reportingTimezone": string | null;
}

export interface SessionDetailResponse {
    "meta": query$0.ResponseMeta;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "unpricedReasons": ReasonCount[] | null;
    "item": SessionItem;
    "degradedReason": DegradedReason | null;
}

export interface SessionItem {
    "sessionId": string;
    "displayTitle": string;
    "titleConfidence": string;
    "titleSource": string;
    "titleReason": string;
    "project": AttributionValue;
    "model": AttributionValue;
    "activity": string;
    "lastActivityAtMs": query$0.NumericValue;
    "totals": UsageTotals;
}

export interface SessionListResponse {
    "meta": query$0.ResponseMeta;
    "pricingSource": string | null;
    "currency": string | null;
    "items": SessionItem[] | null;
    "matchedCount": query$0.NumericValue;
    "matchedTotals": UsageTotals;
    "pageTotals": UsageTotals;
    "degradedReason": DegradedReason | null;
}

export enum TrendGranularity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TrendDay = "day",
    TrendWeek = "week",
    TrendMonth = "month",
};

export interface TrendPoint {
    "key": string;
    "startAtMs": query$0.NumericValue;
    "endAtMs": query$0.NumericValue;
    "totals": UsageTotals;
}

export interface UsageCostRequest {
    "range": query$0.LocalDateRange;
    "granularity": TrendGranularity;
}

export interface UsageCostResponse {
    "meta": query$0.ResponseMeta;
    "range": query$0.UTCTimeRange;
    "reportingTimeZone": string;
    "pricingSource": string | null;
    "currency": string | null;
    "pricingVersions": string[] | null;
    "totals": UsageTotals;
    "trend": TrendPoint[] | null;
    "unpricedReasons": ReasonCount[] | null;
    "degradedReason": DegradedReason | null;
}

export interface UsageTotals {
    "turnCount": query$0.NumericValue;
    "inputTokens": query$0.NumericValue;
    "cachedInputTokens": query$0.NumericValue;
    "outputTokens": query$0.NumericValue;
    "reasoningTokens": query$0.NumericValue;
    "totalTokens": query$0.NumericValue;
    "estimatedUsdMicros": query$0.NumericValue;
    "pricedTurnCount": query$0.NumericValue;
    "unpricedTurnCount": query$0.NumericValue;
    "firstActivityAtMs": query$0.NumericValue;
    "lastActivityAtMs": query$0.NumericValue;
}
