// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum MigrationStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MigrationStageCatalog = "catalog",
    MigrationStageInspect = "inspect",
    MigrationStageSpace = "space",
    MigrationStageBackup = "backup",
    MigrationStageApply = "apply",
    MigrationStageVerify = "verify",
    MigrationStageComplete = "complete",
};

export enum QuotaConflictState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaConflictNone = "none",
    QuotaConflictPresent = "conflict",
};

export enum QuotaCurrentFreshness {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaCurrentNeverLoaded = "never_loaded",
    QuotaCurrentFresh = "fresh",
    QuotaCurrentStale = "stale",
    QuotaCurrentExpiredUnknown = "expired_unknown",
    QuotaCurrentSuspicious = "suspicious",
};

export enum QuotaEvidenceDisposition {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaEvidenceSelected = "selected",
    QuotaEvidenceEligible = "eligible",
    QuotaEvidenceSuperseded = "superseded",
    QuotaEvidenceSuspicious = "suspicious",
    QuotaEvidenceRejected = "rejected",
};

export enum QuotaExplanationCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaExplanationTrusted = "trusted",
    QuotaExplanationStale = "stale",
    QuotaExplanationExpired = "expired_unknown",
    QuotaExplanationSuspicious = "suspicious_candidate",
    QuotaExplanationSourceConflict = "source_conflict",
    QuotaExplanationUnavailable = "unavailable",
};

export enum QuotaRejectionReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaReasonMissingLimitID = "missing_limit_id",
    QuotaReasonMissingPrimaryWindow = "missing_primary_window",
    QuotaReasonResetNotFuture = "reset_not_future",
    QuotaReasonUnknownPlanType = "unknown_plan_type",
    QuotaReasonInvalidUsedPercent = "invalid_used_percent",
    QuotaReasonInvalidWindowMinutes = "invalid_window_minutes",
    QuotaReasonInvalidResetsAt = "invalid_resets_at",
    QuotaReasonInvalidStructure = "invalid_structure",
    QuotaReasonUsedRegression = "used_regression",
    QuotaReasonResetRegression = "reset_regression",
    QuotaReasonObservedRegression = "observed_time_regression",
    QuotaReasonSourceConflict = "source_conflict",
    QuotaReasonDefaultFallback = "default_fallback",
};

export enum QuotaSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaSourceLocalJSONL = "local_jsonl",
    QuotaSourceWham = "wham",
};

export enum QuotaValidity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaValidityAccepted = "accepted",
    QuotaValiditySuspicious = "suspicious",
    QuotaValidityRejected = "rejected",
};

export enum QuotaWindowKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuotaWindowPrimary = "primary",
    QuotaWindowSecondary = "secondary",
};

/**
 * SourceFailureCode keeps a source-specific, content-free failure reason next
 * to the cross-domain RuntimeErrorClass. It is safe for persistence and UI
 * routing because it cannot carry an upstream error or response body.
 */
export enum SourceFailureCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceFailureNetworkUnavailable = "network_unavailable",
    SourceFailureTimeout = "timeout",
    SourceFailureAuthRequired = "auth_required",
    SourceFailureHTTP429 = "http_429",
    SourceFailureServerError = "server_error",
    SourceFailureSchemaIncompatible = "schema_incompatible",
    SourceFailureCancelled = "cancelled",
};

export enum SourceFreshness {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceFreshnessUnknown = "unknown",
    SourceFreshnessCurrent = "current",
    SourceFreshnessStale = "stale",
    SourceFreshnessUnavailable = "unavailable",
};

export enum SourceRefreshReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RefreshReasonStartup = "startup",
    RefreshReasonNormalInterval = "normal_interval",
    RefreshReasonLowRemaining = "low_remaining",
    RefreshReasonNearReset = "near_reset",
    RefreshReasonResetGrace = "reset_grace",
    RefreshReasonForeground = "foreground",
    RefreshReasonWakeStale = "wake_stale",
    RefreshReasonManual = "manual",
    RefreshReasonNetworkBackoff = "network_backoff",
    RefreshReasonRetryAfter = "retry_after",
    RefreshReasonAuthRequired = "auth_required",
    RefreshReasonSchemaIncompatible = "schema_incompatible",
    RefreshReasonCancelled = "cancelled",
    RefreshReasonDisabled = "disabled",
    RefreshReasonRecovery = "recovery",
};

export enum SourceRefreshTrigger {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RefreshTriggerScheduled = "scheduled",
    RefreshTriggerStartup = "startup",
    RefreshTriggerForeground = "foreground",
    RefreshTriggerWake = "wake",
    RefreshTriggerManual = "manual",
    RefreshTriggerRecovery = "recovery",
};
