import type { PaceResponse, QuotaResponse, QuotaWindow } from '../api/quotas';

export const quotaNow=Date.UTC(2026,9,2,1);
export function quotaFixture():QuotaResponse{
 const window:QuotaWindow={key:'window-primary',provider:'codex',account_key:'account-one',identity_state:'confirmed',limit_id:'codex',window_kind:'primary',window_minutes:300,current:{used_percent:0,remaining_percent:100,window_start_at_ms:quotaNow-18000000,resets_at_ms:quotaNow+3600000,reset_remaining_ms:3600000,observed_at_ms:quotaNow,freshness:'fresh',conflict:false,reason:'trusted',selected_observation_id:'point-last',selected_client_id:'machine-one',source:'app_server_rate_limits'},cycles:[],observations:[{id:'point-last',client_id:'machine-one',client_name:'合成采集机',observed_at_ms:quotaNow,received_at_ms:quotaNow+10000,used_percent:0,resets_at_ms:quotaNow+3600000,window_start_at_ms:quotaNow-18000000,source:'app_server_rate_limits',validity:'accepted',history_origin:'confirmed',disposition:'selected',reason:null,cycle_id:'cycle-one',canonical_reset_at_ms:quotaNow+3600000}],coverage:'observed_only'};
 return {evaluated_at_ms:quotaNow,rule_version:'synthetic-rule',coverage:'observed_only',accounts:[{key:'account-one',provider:'codex',raw_id:'raw-account-one',email:'same@example.invalid',plan:'Pro',collected_at_ms:quotaNow},{key:'account-two',provider:'codex',raw_id:'raw-account-two',email:'same@example.invalid',plan:null,collected_at_ms:quotaNow}],windows:[window],credits:[{key:'credit-one',provider:'codex',account_key:'account-one',client_id:'machine-one',observed_at_ms:quotaNow,observed_inventory:'9007199254740993',available_inventory:null,details_status:'partial',freshness:'stale',conflict:false,next_reset_at_ms:null,next_expires_at_ms:quotaNow+86400000,expiry_schedule:[{expires_at_ms:quotaNow+86400000,count:'2'}]}]};
}
export function paceFixture():PaceResponse{
 const quota=quotaFixture(),w=quota.windows[0];
 return {evaluated_at_ms:quotaNow+1000,rule_version:'synthetic-pace',coverage:'observed_only',accounts:quota.accounts,windows:[{...w,elapsed_percent:60,pace_delta_pp:10,forecast:{state:'unavailable',method:'none',exhaust_at_ms:null,lead_before_reset_ms:null,evidence_count:2,evidence_span_ms:1800000,unknown_reason:'evidence_sparse'},current_points:[{observed_at_ms:quotaNow-1800000,elapsed_percent:50,used_percent:80,remaining_percent:20,linked_history:false},{observed_at_ms:quotaNow,elapsed_percent:60,used_percent:70,remaining_percent:30,linked_history:false}],previous_cycle:null,historical_cycles:[],history_band:[],history_cycle_count:0,previous_remaining_at_elapsed:null,history_median_remaining_at_elapsed:null,unknown_reason:null}]};
}
