// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum CostReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CostReasonPriced = "priced",
    CostReasonMissingAttribution = "missing_attribution",
    CostReasonMissingModel = "missing_model",
    CostReasonConflictModel = "conflict_model",
    CostReasonInvalidModel = "invalid_model",
    CostReasonCatalogNotEffective = "catalog_not_effective",
    CostReasonModelNotListed = "model_not_listed",
    CostReasonMissingToken = "missing_token",
    CostReasonMissingPriceComponent = "missing_price_component",
};
