// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../store/models.js";

export interface CurrentExplanation {
    "observationId": string;
    "source": store$0.QuotaSource;
    "usedPercent": number | null;
    "remainingPercent": number | null;
    "windowMinutes": number | null;
    "resetsAtMs": number | null;
    "windowGeneration": number | null;
    "observedAtMs": number;
    "validity": store$0.QuotaValidity;
    "disposition": store$0.QuotaEvidenceDisposition;
    "reason": store$0.QuotaRejectionReason | null;
    "explanationCode": store$0.QuotaExplanationCode;
}

export interface CurrentNextReset {
    "atMs": number | null;
    "remainingMs": number | null;
    "trustedWindowCount": number;
    "unknownReason": CurrentUnknownReason | null;
}

export interface CurrentRefresh {
    "quota": CurrentRefreshStatus;
    "resetCredits": CurrentRefreshStatus;
}

export enum CurrentRefreshState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CurrentRefreshUnknown = "unknown",
    CurrentRefreshScheduled = "scheduled",
    CurrentRefreshPaused = "paused",
    CurrentRefreshInFlight = "in_flight",
    CurrentRefreshDisabled = "disabled",
};

export interface CurrentRefreshStatus {
    "state": CurrentRefreshState;
    "nextDueAtMs": number | null;
    "reason": store$0.SourceRefreshReason | null;
    "lastManualAtMs": number | null;
    "activeTrigger": store$0.SourceRefreshTrigger | null;
    "claimStartedAtMs": number | null;
    "claimExpiresAtMs": number | null;
    "unknownReason": CurrentUnknownReason | null;
}

export interface CurrentResetCredits {
    "availableCount": number | null;
    "totalCount": number | null;
    "redeemedCount": number | null;
    "cumulativeRemainingMs": number | null;
    "nextExpiresAtMs": number | null;
    "lastSuccessAtMs": number | null;
    "lastAttemptAtMs": number | null;
    "freshness": store$0.SourceFreshness;
    "failureCode": store$0.SourceFailureCode | null;
    "unknownReason": CurrentUnknownReason | null;
}

export interface CurrentResponse {
    "version": string;
    "accountScope": string;
    "evaluatedAtMs": number;
    "windows": CurrentWindow[] | null;
    "sources": CurrentSource[] | null;
    "nextReset": CurrentNextReset;
    "resetCredits": CurrentResetCredits;
    "refresh": CurrentRefresh;
}

export interface CurrentSource {
    "source": CurrentSourceKind;
    "lastObservedAtMs": number | null;
    "lastSuccessAtMs": number | null;
    "lastAttemptAtMs": number | null;
    "freshness": store$0.SourceFreshness;
    "failureCode": store$0.SourceFailureCode | null;
    "selectedWindowCount": number;
    "conflictWindowCount": number;
    "unknownReason": CurrentUnknownReason | null;
}

export enum CurrentSourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CurrentSourceLocal = "local_jsonl",
    CurrentSourceWham = "wham",
};

export enum CurrentUnknownReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CurrentUnknownNeverLoaded = "never_loaded",
    CurrentUnknownNoTrustedReset = "no_trusted_reset",
    CurrentUnknownSourceUnavailable = "source_unavailable",
    CurrentUnknownScheduleMissing = "schedule_unavailable",
};

export interface CurrentWindow {
    "windowKind": store$0.QuotaWindowKind;
    "limitId": string;
    "usedPercent": number | null;
    "remainingPercent": number | null;
    "windowMinutes": number | null;
    "resetsAtMs": number | null;
    "resetRemainingMs": number | null;
    "windowGeneration": number | null;
    "selectedSource": store$0.QuotaSource | null;
    "freshness": store$0.QuotaCurrentFreshness;
    "conflict": store$0.QuotaConflictState;
    "explanationCode": store$0.QuotaExplanationCode;
    "unknownReason": CurrentUnknownReason | null;
    "lastSuccessAtMs": number | null;
    "lastAttemptAtMs": number | null;
    "explanations": CurrentExplanation[] | null;
}
