// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3826773154);
}

export function Confirm(token: string): $CancellablePromise<$models.MigrationRecoveryReceipt> {
    return $Call.ByID(3998988744, token);
}

export function Exit(): $CancellablePromise<void> {
    return $Call.ByID(2778291256);
}

export function Prepare(backupName: string): $CancellablePromise<$models.MigrationRestoreConfirmation> {
    return $Call.ByID(4276913483, backupName);
}

export function Retry(): $CancellablePromise<$models.MigrationRecoveryReceipt> {
    return $Call.ByID(3256929226);
}

export function State(): $CancellablePromise<$models.MigrationRecoverySnapshot> {
    return $Call.ByID(1028103661);
}
