// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../query/models.js";

export interface BindingContractInfo {
    "version": string;
    "queryVersion": string;
    "usageCostVersion": string;
    "runtimeInfoVersion": string;
    "methods": BindingMethodInfo[] | null;
    "commandMethods": string[] | null;
    "errorExample": query$0.ErrorEnvelope;
}

export interface BindingMethodInfo {
    "name": string;
    "kind": BindingMethodKind;
}

export enum BindingMethodKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BindingMethodQuery = "query",
    BindingMethodCommand = "command",
};

/**
 * BootstrapInfo contains the non-sensitive metadata needed to render the
 * application shell.
 */
export interface BootstrapInfo {
    "name": string;
    "locale": string;
    "platform": string;
}
