// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as quota$0 from "../codex/quota/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../query/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

export interface BindingContractInfo {
    "version": string;
    "queryVersion": string;
    "usageCostVersion": string;
    "runtimeInfoVersion": string;
    "methods": BindingMethodInfo[] | null;
    "commandMethods": string[] | null;
    "errorExample": query$0.ErrorEnvelope;
}

export interface BindingMethodInfo {
    "name": string;
    "kind": BindingMethodKind;
}

export enum BindingMethodKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BindingMethodQuery = "query",
    BindingMethodCommand = "command",
};

/**
 * BootstrapInfo contains the non-sensitive metadata needed to render the
 * application shell.
 */
export interface BootstrapInfo {
    "name": string;
    "locale": string;
    "platform": string;
}

export interface HomeSwitchPlanReceipt {
    "strategy": HomeSwitchStrategy;
    "targetGeneration": string;
    "preservesOldFacts": boolean;
    "clearsDerivedFacts": boolean;
}

export interface HomeSwitchPlanRequest {
    "targetPath": string;
    "strategy": HomeSwitchStrategy;
}

export interface HomeSwitchReceipt {
    "revision": string;
    "generation": string;
    "result": HomeSwitchResult;
}

export enum HomeSwitchResult {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HomeSwitchCompletedResult = "completed",
    HomeSwitchRolledBackResult = "rolled_back",
    HomeSwitchRecoveryRequired = "recovery_required",
};

export enum HomeSwitchStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HomeSwitchIndependentDatabase = "independent_database",
    HomeSwitchClearAndRebuild = "clear_and_rebuild",
};

export enum QueryInvalidationDomain {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QueryInvalidationIndex = "index",
    QueryInvalidationQuota = "quota",
    QueryInvalidationHealth = "health",
    QueryInvalidationSettings = "settings",
};

/**
 * QueryInvalidationEvent is a best-effort cache hint. It deliberately carries
 * no business fact; the frontend must refetch the authoritative Go query.
 */
export interface QueryInvalidationEvent {
    "version": QueryInvalidationVersion;
    "domain": QueryInvalidationDomain;
}

export enum QueryInvalidationVersion {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QueryInvalidationContractVersion = "query-invalidation-v1",
};

export interface QuotaRefreshReceipt {
    "source": quota$0.RefreshSource;
    "nextDueAtMs": number | null;
    "reason": store$0.SourceRefreshReason;
    "lastManualAtMs": number | null;
}

export interface RepairDryRunReceipt {
    "analyzedAtMs": number;
    "actionCount": number;
    "conflictCount": number;
    "historyCount": number;
    "diagnosticCount": number;
    "noop": boolean;
}

export enum RuntimeAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeActionPauseBackfill = "pause_backfill",
    RuntimeActionPauseAll = "pause_all",
    RuntimeActionResume = "resume",
    RuntimeActionReconcile = "reconcile",
};

export interface RuntimeActionReceipt {
    "action": RuntimeAction;
    "pauseScope": string;
    "sourceState": string;
    "transition": string;
}

export interface SettingsOnlineUpdate {
    "quotaEnabled": boolean;
    "resetCreditsEnabled": boolean;
}

export interface SettingsRefreshUpdate {
    "quotaIntervalSeconds": number;
    "resetCreditsIntervalSeconds": number;
    "reconcileIntervalSeconds": number;
    "jsonlDebounceMilliseconds": number;
}

export interface SettingsUIUpdate {
    "launchBehavior": string;
    "overviewRange": string;
}

export interface SettingsUpdateReceipt {
    "revision": string;
    "result": SettingsUpdateResult;
}

export interface SettingsUpdateRequest {
    "expectedRevision": string;
    "online": SettingsOnlineUpdate;
    "refresh": SettingsRefreshUpdate;
    "updates": SettingsUpdatesUpdate;
    "ui": SettingsUIUpdate;
}

export enum SettingsUpdateResult {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SettingsUpdateApplied = "applied",
    SettingsUpdateReconcileRequired = "applied_reconcile_required",
};

export interface SettingsUpdatesUpdate {
    "autoCheckEnabled": boolean;
    "checkIntervalSeconds": number;
}
