// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the only business service registered with Wails. Its unexported
 * dependencies keep Store, Preferences, filesystem and credential primitives
 * outside the generated frontend surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as quota$0 from "../codex/quota/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../query/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtimeinfo$0 from "../query/runtimeinfo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usagecost$0 from "../query/usagecost/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AnalyzeSessionIndexRepair(): $CancellablePromise<$models.RepairDryRunReceipt> {
    return $Call.ByID(2801159080);
}

export function Bootstrap(): $CancellablePromise<$models.BootstrapInfo> {
    return $Call.ByID(1557176803);
}

export function CancelUpdate(): $CancellablePromise<$models.UpdateActionReceipt> {
    return $Call.ByID(2687146184);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateTriggerReceipt> {
    return $Call.ByID(3322628226);
}

export function ConfirmHomeSwitch(): $CancellablePromise<$models.HomeSwitchReceipt> {
    return $Call.ByID(853820626);
}

export function Contracts(): $CancellablePromise<$models.BindingContractInfo> {
    return $Call.ByID(3089117070);
}

export function DataHealth(evaluatedAtMS: number): $CancellablePromise<runtimeinfo$0.DataHealthResponse> {
    return $Call.ByID(3278814177, evaluatedAtMS);
}

export function DownloadUpdate(): $CancellablePromise<$models.UpdateActionReceipt> {
    return $Call.ByID(3553712314);
}

export function Health(request: runtimeinfo$0.HealthDetailRequest): $CancellablePromise<runtimeinfo$0.HealthDetailResponse> {
    return $Call.ByID(1359498569, request);
}

export function HealthProjection(): $CancellablePromise<$models.HealthProjectionResponse> {
    return $Call.ByID(2606310108);
}

export function InstallUpdate(): $CancellablePromise<$models.UpdateActionReceipt> {
    return $Call.ByID(1370610399);
}

export function Job(request: runtimeinfo$0.JobDetailRequest): $CancellablePromise<runtimeinfo$0.JobDetailResponse> {
    return $Call.ByID(3305728438, request);
}

export function ListHealth(request: query$0.Request): $CancellablePromise<runtimeinfo$0.HealthListResponse> {
    return $Call.ByID(720491425, request);
}

export function ListJobs(request: query$0.Request): $CancellablePromise<runtimeinfo$0.JobListResponse> {
    return $Call.ByID(269030631, request);
}

export function ListProjects(request: query$0.Request): $CancellablePromise<usagecost$0.ProjectListResponse> {
    return $Call.ByID(2263002677, request);
}

export function ListSessions(request: query$0.Request): $CancellablePromise<usagecost$0.SessionListResponse> {
    return $Call.ByID(2042546646, request);
}

export function ListSources(request: query$0.Request): $CancellablePromise<runtimeinfo$0.SourceListResponse> {
    return $Call.ByID(3661465571, request);
}

export function PlanHomeSwitch(request: $models.HomeSwitchPlanRequest): $CancellablePromise<$models.HomeSwitchPlanReceipt> {
    return $Call.ByID(3604705039, request);
}

export function ProjectDetail(request: usagecost$0.ProjectDetailRequest): $CancellablePromise<usagecost$0.ProjectDetailResponse> {
    return $Call.ByID(728158813, request);
}

export function QuotaCurrent(evaluatedAtMS: number): $CancellablePromise<runtimeinfo$0.QuotaCurrentResponse> {
    return $Call.ByID(2925790970, evaluatedAtMS);
}

export function RecoverHomeSwitch(): $CancellablePromise<$models.HomeSwitchReceipt> {
    return $Call.ByID(3014210070);
}

export function RequestQuotaRefresh(source: quota$0.RefreshSource): $CancellablePromise<$models.QuotaRefreshReceipt> {
    return $Call.ByID(92566339, source);
}

export function RunRuntimeAction(action: $models.RuntimeAction): $CancellablePromise<$models.RuntimeActionReceipt> {
    return $Call.ByID(2851045070, action);
}

export function SessionDetail(request: usagecost$0.SessionDetailRequest): $CancellablePromise<usagecost$0.SessionDetailResponse> {
    return $Call.ByID(1175479752, request);
}

export function Settings(): $CancellablePromise<runtimeinfo$0.SettingsResponse> {
    return $Call.ByID(202944386);
}

export function SkipUpdate(version: string): $CancellablePromise<$models.UpdateActionReceipt> {
    return $Call.ByID(1076401141, version);
}

export function SnoozeUpdate(seconds: number): $CancellablePromise<$models.UpdateActionReceipt> {
    return $Call.ByID(2703867884, seconds);
}

export function Source(request: runtimeinfo$0.SourceDetailRequest): $CancellablePromise<runtimeinfo$0.SourceDetailResponse> {
    return $Call.ByID(89156586, request);
}

export function UpdateSettings(request: $models.SettingsUpdateRequest): $CancellablePromise<$models.SettingsUpdateReceipt> {
    return $Call.ByID(4235621163, request);
}

export function UpdateState(): $CancellablePromise<$models.UpdateStateResponse> {
    return $Call.ByID(3406509219);
}

export function UsageCost(request: usagecost$0.UsageCostRequest): $CancellablePromise<usagecost$0.UsageCostResponse> {
    return $Call.ByID(915630367, request);
}
