// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the only business service registered with Wails. Its unexported
 * dependencies keep Store, Preferences, filesystem and credential primitives
 * outside the generated frontend surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../query/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtimeinfo$0 from "../query/runtimeinfo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usagecost$0 from "../query/usagecost/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Bootstrap(): $CancellablePromise<$models.BootstrapInfo> {
    return $Call.ByID(1557176803);
}

export function Contracts(): $CancellablePromise<$models.BindingContractInfo> {
    return $Call.ByID(3089117070);
}

export function Health(request: runtimeinfo$0.HealthDetailRequest): $CancellablePromise<runtimeinfo$0.HealthDetailResponse> {
    return $Call.ByID(1359498569, request);
}

export function Job(request: runtimeinfo$0.JobDetailRequest): $CancellablePromise<runtimeinfo$0.JobDetailResponse> {
    return $Call.ByID(3305728438, request);
}

export function ListHealth(request: query$0.Request): $CancellablePromise<runtimeinfo$0.HealthListResponse> {
    return $Call.ByID(720491425, request);
}

export function ListJobs(request: query$0.Request): $CancellablePromise<runtimeinfo$0.JobListResponse> {
    return $Call.ByID(269030631, request);
}

export function ListProjects(request: query$0.Request): $CancellablePromise<usagecost$0.ProjectListResponse> {
    return $Call.ByID(2263002677, request);
}

export function ListSessions(request: query$0.Request): $CancellablePromise<usagecost$0.SessionListResponse> {
    return $Call.ByID(2042546646, request);
}

export function ListSources(request: query$0.Request): $CancellablePromise<runtimeinfo$0.SourceListResponse> {
    return $Call.ByID(3661465571, request);
}

export function ProjectDetail(request: usagecost$0.ProjectDetailRequest): $CancellablePromise<usagecost$0.ProjectDetailResponse> {
    return $Call.ByID(728158813, request);
}

export function QuotaCurrent(evaluatedAtMS: number): $CancellablePromise<runtimeinfo$0.QuotaCurrentResponse> {
    return $Call.ByID(2925790970, evaluatedAtMS);
}

export function SessionDetail(request: usagecost$0.SessionDetailRequest): $CancellablePromise<usagecost$0.SessionDetailResponse> {
    return $Call.ByID(1175479752, request);
}

export function Settings(): $CancellablePromise<runtimeinfo$0.SettingsResponse> {
    return $Call.ByID(202944386);
}

export function Source(request: runtimeinfo$0.SourceDetailRequest): $CancellablePromise<runtimeinfo$0.SourceDetailResponse> {
    return $Call.ByID(89156586, request);
}

export function UsageCost(request: usagecost$0.UsageCostRequest): $CancellablePromise<usagecost$0.UsageCostResponse> {
    return $Call.ByID(915630367, request);
}
