// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as quota$0 from "../../codex/quota/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../models.js";

export interface EditableField {
    "key": string;
    "type": EditableValueType;
    "editable": boolean;
    "minimum": number | null;
    "maximum": number | null;
    "options": string[] | null;
}

export enum EditableValueType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EditableBoolean = "boolean",
    EditableInteger = "integer",
    EditableEnum = "enum",
};

export interface HealthDetailRequest {
    "eventId": string;
}

export interface HealthDetailResponse {
    "meta": query$0.ResponseMeta;
    "item": HealthItem;
}

export interface HealthItem {
    "eventId": string;
    "domain": string;
    "severity": string;
    "code": string;
    "component": string;
    "rule": string;
    "impact": string;
    "protection": string;
    "sourceKey": string | null;
    "jobId": string | null;
    "errorClass": string | null;
    "firstSeenAtMs": query$0.NumericValue;
    "lastSeenAtMs": query$0.NumericValue;
    "resolvedAtMs": query$0.NumericValue;
    "occurrenceCount": query$0.NumericValue;
    "active": boolean;
    "recoveryAction": RecoveryAction;
}

export enum HealthLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HealthHealthy = "healthy",
    HealthBusy = "busy",
    HealthPaused = "paused",
    HealthDegraded = "degraded",
    HealthBlocked = "blocked",
};

export interface HealthListResponse {
    "meta": query$0.ResponseMeta;
    "items": HealthItem[] | null;
    "matchedCount": query$0.NumericValue;
    "summary": HealthSummary;
}

export interface HealthSummary {
    "level": HealthLevel;
    "total": query$0.NumericValue;
    "active": query$0.NumericValue;
    "resolved": query$0.NumericValue;
    "info": query$0.NumericValue;
    "warnings": query$0.NumericValue;
    "errors": query$0.NumericValue;
    "critical": query$0.NumericValue;
}

export enum HomeSwitchStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HomeSwitchStable = "stable",
    HomeSwitchPending = "pending",
    HomeSwitchRecoveryRequired = "recovery_required",
};

export interface JobDetailRequest {
    "jobId": string;
}

export interface JobDetailResponse {
    "meta": query$0.ResponseMeta;
    "item": JobItem;
}

export interface JobItem {
    "jobId": string;
    "jobType": string;
    "requestedBy": string;
    "state": string;
    "phase": string;
    "sourceKey": string | null;
    "createdAtMs": query$0.NumericValue;
    "startedAtMs": query$0.NumericValue;
    "finishedAtMs": query$0.NumericValue;
    "lastSuccessAtMs": query$0.NumericValue;
    "progress": JobProgress;
    "failureCount": query$0.NumericValue;
    "nextRetryAtMs": query$0.NumericValue;
    "errorClass": string | null;
    "updatedAtMs": query$0.NumericValue;
    "recoveryAction": RecoveryAction;
}

export interface JobListResponse {
    "meta": query$0.ResponseMeta;
    "items": JobItem[] | null;
    "matchedCount": query$0.NumericValue;
    "summary": JobSummary;
}

export interface JobProgress {
    "current": query$0.NumericValue;
    "total": query$0.NumericValue;
}

export interface JobSummary {
    "total": query$0.NumericValue;
    "queued": query$0.NumericValue;
    "running": query$0.NumericValue;
    "succeeded": query$0.NumericValue;
    "failed": query$0.NumericValue;
    "cancelled": query$0.NumericValue;
    "interrupted": query$0.NumericValue;
}

export interface QuotaCurrentResponse {
    "meta": query$0.ResponseMeta;
    "current": quota$0.CurrentResponse;
}

export interface RecoveryAction {
    "kind": RecoveryActionKind;
    "commandKey": string | null;
}

export enum RecoveryActionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RecoveryNone = "none",
    RecoveryRetry = "retry",
    RecoveryCheckSource = "check_source",
    RecoveryGrantPermission = "grant_permission",
    RecoveryFreeSpace = "free_space",
    RecoveryChooseHome = "choose_home",
    RecoveryRepairStore = "repair_store",
};

export interface SettingsHomeSnapshot {
    "configured": boolean;
    "generation": string;
    "switchStatus": HomeSwitchStatus;
    "lastSwitchOutcome": string | null;
}

export interface SettingsOnlineSnapshot {
    "quotaEnabled": boolean;
    "resetCreditsEnabled": boolean;
}

export interface SettingsRefreshSnapshot {
    "quotaIntervalSeconds": number;
    "resetCreditsIntervalSeconds": number;
    "reconcileIntervalSeconds": number;
    "jsonlDebounceMilliseconds": number;
}

export interface SettingsResponse {
    "meta": query$0.ResponseMeta;
    "snapshot": SettingsSnapshot;
    "editableFields": EditableField[] | null;
}

export interface SettingsSnapshot {
    "schemaVersion": number;
    "revision": string;
    "onboardingCompleted": boolean;
    "home": SettingsHomeSnapshot;
    "online": SettingsOnlineSnapshot;
    "refresh": SettingsRefreshSnapshot;
    "updates": SettingsUpdateSnapshot;
    "ui": SettingsUISnapshot;
}

export interface SettingsUISnapshot {
    "locale": string;
    "launchBehavior": string;
    "overviewRange": string;
}

export interface SettingsUpdateSnapshot {
    "autoCheckEnabled": boolean;
    "autoDownloadEnabled": boolean;
    "channel": string;
    "checkIntervalSeconds": number;
    "skippedVersion": string | null;
    "snoozeUntilMs": query$0.NumericValue;
    "lastCheckAtMs": query$0.NumericValue;
}

export interface SourceDetailRequest {
    "sourceKey": string;
}

export interface SourceDetailResponse {
    "meta": query$0.ResponseMeta;
    "item": SourceItem;
}

export interface SourceItem {
    "sourceKey": string;
    "kind": SourceKind;
    "provider": string | null;
    "sourceType": string | null;
    "state": string;
    "sizeBytes": query$0.NumericValue;
    "parsedBytes": query$0.NumericValue;
    "lastScannedAtMs": query$0.NumericValue;
    "lastAttemptAtMs": query$0.NumericValue;
    "lastSuccessAtMs": query$0.NumericValue;
    "nextDueAtMs": query$0.NumericValue;
    "consecutiveFailures": query$0.NumericValue;
    "errorClass": string | null;
    "failureCode": string | null;
    "updatedAtMs": query$0.NumericValue;
    "recoveryAction": RecoveryAction;
}

export enum SourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceLocalFile = "local_file",
    SourceOnline = "online",
};

export interface SourceListResponse {
    "meta": query$0.ResponseMeta;
    "items": SourceItem[] | null;
    "matchedCount": query$0.NumericValue;
    "summary": SourceSummary;
    "unavailableKinds": SourceKind[] | null;
}

export interface SourceSummary {
    "total": query$0.NumericValue;
    "localFiles": query$0.NumericValue;
    "onlineSources": query$0.NumericValue;
    "attention": query$0.NumericValue;
}
